---
title: "Seasonal Comparison"
author: "Eden Axelrad"
date: "9/5/2019"
output: html_document
---

<br>


```{r setup, include=FALSE}

#setup and cleaning data

library("tidyverse")
library("scales")
library("MASS")
library("viridis")
library("DT")
library("rcompanion")
library("ggpubr")
library("car")
library("e1071") 
library("gridExtra")
library("reshape2")
library("lubridate")
library("visdat")

setwd("/Users/edenaxelrad/Desktop/Green Roofs (Thesis)/Summer Run")

avg_summer <- read.csv("Interior Avgs.csv", stringsAsFactors = FALSE)
avg_summer <- avg_summer[4:1587,]
avg_summer$Sample_Number <- 1:1584
avg_summer$timestamp <- mdy_hm(avg_summer$Date.Time)
avg_summer$timestamp <- avg_summer$timestamp - minutes(120)
avg_summer$hour <- hour(avg_summer$timestamp)
avg_summer$day <- date(avg_summer$timestamp)
avg_summer <- avg_summer[,c(1,8,9,10,3:7)]
avg_summer$season <- "summer"

avg_spring <- read.csv("spring interior avgs.csv", stringsAsFactors = FALSE)
avg_spring <- avg_spring[1:1680,]
avg_spring$timestamp <- mdy_hm(avg_spring$Date.Time)
avg_spring$hour <- hour(avg_spring$timestamp)
avg_spring$day <- date(avg_spring$timestamp)
avg_spring <- avg_spring[,c(1,8,9,10,3:7)]
avg_spring$season <- "spring"

summerR <- cbind.data.frame(avg_summer$Sedum.rubro, 
                            avg_summer$rubro.vs.substrate, 
                            hour(avg_summer$timestamp), 
                            "summer")
colnames(summerR) <- c("temp", "diff", "hour", "season")
springR <- cbind.data.frame(avg_spring$Sedum.rubro, 
                            avg_spring$rubro.vs.substrate, 
                            hour(avg_spring$timestamp), 
                            "spring")
colnames(springR) <- c("temp", "diff", "hour", "season")
seasonalR <- rbind.data.frame(summerR, springR)

summerA <- cbind.data.frame(avg_summer$Sedum.acre, 
                            avg_summer$acre.vs.substrate, 
                            hour(avg_summer$timestamp), 
                            "summer")
colnames(summerA) <- c("temp", "diff", "hour", "season")
springA <- cbind.data.frame(avg_spring$Sedum.acre, 
                            avg_spring$acre.vs.substrate, 
                            hour(avg_spring$timestamp), 
                            "spring")
colnames(springA) <- c("temp", "diff", "hour", "season")
seasonalA <- rbind.data.frame(summerA, springA)

both_seasons <- rbind.data.frame(avg_spring, avg_summer)
```

### Temperature By Hour

<br>

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.align="center"}

ggplot(seasonalR, aes(seasonalR$hour, seasonalR$diff)) + 
  geom_hline(yintercept=0, color = "black", alpha = .5) +
  geom_point(aes(color = season), alpha = .5) +
  geom_smooth(aes(color = season), se = FALSE) + 
  ggtitle("(a) Sedum rubro - Bare Substrate by Season") + 
  ylab("Temperature Difference") + 
  xlab("Hour") + 
  labs(color = "Season")

```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.align="center"}

ggplot(seasonalA, aes(seasonalA$hour, seasonalA$diff)) + 
  geom_hline(yintercept=0, color = "black", alpha = .5) +
  geom_point(aes(color = season), alpha = .5) +
  geom_smooth(aes(color = season), se = FALSE) + 
  ggtitle("(b) Sedum acre - Bare Substrate by Season") + 
  ylab("Temperature Difference") + 
  xlab("Hour") + 
  labs(color = "Season")

```

### Linear Models

```{r, fig.width=6, fig.height=6, echo=FALSE, fig.align="center", warning=FALSE}

ggplot(both_seasons, aes(x=bare.substrate, y=Sedum.rubro)) + 
  geom_point(alpha = .5) +
  geom_smooth(aes(color = season), method = "lm")+
  ylim(7.5,45) + xlim(7.5,45) +
  ylab("sedum rubro")+
  xlab("bare substrate")+
  geom_abline(b=1, color="black", linetype=2)+
  ggtitle("(a) Linear Model of soil ~ Sedum rubrotinctum")

```

```{r, fig.width=6, fig.height=6, echo=FALSE, fig.align="center", warning=FALSE}

ggplot(both_seasons, aes(x=bare.substrate, y=Sedum.acre)) + 
  geom_point(alpha = .5)+
  geom_smooth(aes(color = season), method = "lm")+
  ylim(7.5,45) + xlim(7.5,45) +
  ylab("sedum acre")+
  xlab("bare substrate")+
  geom_abline(b=1, color="black", linetype=2)+
  ggtitle("(b) Linear Model of soil ~ Sedum acre")

```

### Hourly Temperature Averages by Treatment
```{r, echo=FALSE, fig.align="center"}

hrly_spring <-
  avg_spring %>%
  group_by(hour) %>%
  summarize(mean(Sedum.rubro), mean(Sedum.acre), mean(bare.substrate))

hrly_summer <-
  avg_summer %>%
  group_by(hour) %>%
  summarize(mean(Sedum.rubro), mean(Sedum.acre), mean(bare.substrate))

plot(hrly_spring$hour, hrly_spring$`mean(Sedum.rubro)`, type = "l", col = "blue",
     main = "Hourly Temperature Averages - Sedum rubrotinctum",
     xlab = "Hour",
     ylim = c(5,40),
     ylab = "Avg Temperature (C)")
lines(hrly_spring$hour, hrly_spring$`mean(bare.substrate)`, lty = 3, col = "darkblue")
lines(hrly_summer$hour, hrly_summer$`mean(Sedum.rubro)`, col="red")
lines(hrly_summer$hour, hrly_summer$`mean(bare.substrate)`, lty = 3, col = "darkred")
legend("topleft", legend = c("Spring - rubro", "Spring - soil", "Summer - rubro", "Summer - soil"), col = c("blue", "darkblue", "red", "darkred"), lty=c(1,3,1,3), box.lty=0)

plot(hrly_spring$hour, hrly_spring$`mean(Sedum.acre)`, type = "l", col = "blue",
     main = "Hourly Temperature Averages - Sedum acre",
     xlab = "Hour",
     ylim = c(5,40),
     ylab = "Avg Temperature (C)")
lines(hrly_spring$hour, hrly_spring$`mean(bare.substrate)`, lty = 3, col = "darkblue")
lines(hrly_summer$hour, hrly_summer$`mean(Sedum.acre)`, col="red")
lines(hrly_summer$hour, hrly_summer$`mean(bare.substrate)`, lty = 3, col = "darkred")
legend("topleft", legend = c("Spring - acre", "Spring - soil", "Summer - acre", "Summer - soil"), col = c("blue", "darkblue", "red", "darkred"), lty=c(1,3,1,3), box.lty=0)
```


